### ISSUE TITLE
Unable to launch gui.py - getting an error in underlying code...

### ISSUE THREAD

**Issue by JAFairweather** [perusworld/python-barcode-reader#1]
Receiving the following error -

mendel@indigo-bunny:~/coral/python-barcode/python-barcode-reader/opencv$ python3 gui.py
[INFO] starting video stream...
Unable to stop the stream: Invalid argument
Traceback (most recent call last):
  File "gui.py", line 16, in <module>
    for decoded in decode.decode(frame):
  File "/home/mendel/coral/python-barcode/python-barcode-reader/opencv/barcode.py", line 6, in decode
    barcodes = pyzbar.decode(frame)
  File "/home/mendel/.local/lib/python3.7/site-packages/pyzbar/pyzbar.py", line 181, in decode
    pixels, width, height = _pixel_data(image)
  File "/home/mendel/.local/lib/python3.7/site-packages/pyzbar/pyzbar.py", line 147, in _pixel_data
    pixels, width, height = image
TypeError: cannot unpack non-iterable NoneType object

**Comment by perusworld** [comment]
does this error occur while starting the program or while scanning the barcode ?

**Comment by perusworld** [comment]
closing, let me know if you have more info
